### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by anselb** [mhinojosa24/Jack-Sparrow-Tweet-Generator#1]
- The spacing in `histogram.py` is good. I like code that separates the variable declaration from the control flow. It could be more consistent though, like removing the space at line 53, or line 44 in `dictionary_words.py`
- The error handling for `dictionary_words.py` puts me into an infinite loop
- In `histogram` in `histogram.py`, there is a small bug.
- If you borrow code, be sure to credit whoever wrote the code in a comment near the borrowed code.
- The comments throughout your code that explain what code does is good and helps readability.

**Comment by mhinojosa24** [comment]
Working on it, thanks for the feedback!
