### ISSUE TITLE
Feedback: LinkedList

### ISSUE THREAD

**Issue by Austrie** [mhinojosa24/Jack-Sparrow-Tweet-Generator#2]
* Good job passing all tests
* Some docstrings are missing runtime analysis (e.g. `is_empty` and `delete`)
* Left in a print statement
* Could optimize your `find` and `delete` methods by checking `tail` (find and delete) and `head` (just delete)  in advance (before the loop)
* Good job having comments in code

**Comment by mhinojosa24** [comment]
Thank you Austrie, I appreciate your feedback.
