### ISSUE TITLE
Feedback: HashTable

### ISSUE THREAD

**Issue by anselb** [mhinojosa24/Jack-Sparrow-Tweet-Generator#3]
- Please try analyzing the runtime of each method. I think you should be able to fill some in based on what you learned in class. For example, in `keys`, if you are looping through all items in all of the buckets, what do you think the runtime is?
- Your code styling looks good; the only things that my flake8 linter suggest is that you shorten line 136 and give two spaces between code and comments on line 136 and 137. Be sure to delete the `TODOs` when you’re done with them. I also recommend moving the comments next to where they happen in the code.

**Comment by mhinojosa24** [comment]
Definitely Working on it, thanks for the feedback!
