### ISSUE TITLE
Tweet Generator Flask, Markov, Listogram/Dictogram and sampling FeedBack

### ISSUE THREAD

**Issue by Novandev** [mhinojosa24/Jack-Sparrow-Tweet-Generator#4]
- Flask app up and live
- First order Markov chain functional( You should try for the 2nd order one)
- Dictogram fails a single assertion test( you're close !)
- Listogram passes all tests
- Code could stand to use a few more comments for better readability

**Comment by mhinojosa24** [comment]
Thanks for the feed!
